apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-buildah-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/source/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build
      image: piyushgarg/buildah
      args: ['bud', '--tls-verify=true', '--layers', '-f', '/source/Dockerfile', '-t', '${outputs.resources.builtImage.url}', '.']
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
    - name: push
      image: piyushgarg/buildah
      args: ['push', '--tls-verify=true', '${outputs.resources.builtImage.url}', 'docker://${outputs.resources.builtImage.url}']
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}