apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-s2i-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
  - name: s2ibuild
    image: quay.io/chmouel/source-to-image:latest
    command: ['/usr/local/bin/s2i']
    args:
    - build
    - ${inputs.resources.source.url}
    - nodeshift/centos7-s2i-nodejs:latest
    - ${outputs.resources.builtImage.url}
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  - name: docker-push
    image: gcr.io/cloud-builders/docker
    args:
    - push
    - ${outputs.resources.builtImage.url}
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket